name: Create Release
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: Releases/rio-os.iso
          name: Rio-OS ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
